aws_dbt_snowflake_project:
  outputs:
    dev:
      account: TXWNVVL-RG31842
      database: AIRBNB
      password: Password@12345
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: JASSNOWFLAKE
      warehouse: COMPUTE_WH
  target: dev
